//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobPortalApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyDetail
    {
        public long CompanyId { get; set; }
        public string CompanyName { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> LastDate { get; set; }
        public Nullable<decimal> CTC { get; set; }
        public string RegistrationId { get; set; }
    }
}
