//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobPortalApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EducationDetail
    {
        public long EducationId { get; set; }
        public string EducationName { get; set; }
        public string PassoutYear { get; set; }
        public string University { get; set; }
        public Nullable<System.Guid> RegisterId { get; set; }
        public string Percentage { get; set; }
    }
}
