//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobPortalApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UniversityDetail
    {
        public int UniversityId { get; set; }
        public string Uname { get; set; }
        public string Location { get; set; }
        public string Established { get; set; }
        public string Specilization { get; set; }
    }
}
